name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Get the short commit hash
    - name: Get short commit hash
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        REPO_OWNER=$(echo "$" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "$" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG2=telegram-downloader
        docker build . --file telegram-downloader/Dockerfile --tag ghcr.io/$REPO_OWNER/$REPO_NAME:${IMAGE_TAG2}
        docker tag ghcr.io/$REPO_OWNER/$REPO_NAME:${IMAGE_TAG} ghcr.io/$REPO_OWNER/$REPO_NAME:latest

    # Push the Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        REPO_OWNER=$(echo "$" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "$" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG=$([[ "$" == "push" && "$" =~ ^refs/tags/ ]] && echo "$" || echo "$")
        docker push ghcr.io/$REPO_OWNER/$REPO_NAME:${IMAGE_TAG}
        docker push ghcr.io/$REPO_OWNER/$REPO_NAME:latest
